### ISSUE TITLE
Plugin and theme commands break on custom folder structures

### ISSUE THREAD

**Issue by kkmuffme** [wp-cli/extension-command#247] opened 2020-08-02 19:28 UTC
followup to https://github.com/wp-cli/extension-command/issues/243

WP-CLI: 2.5.0-alpha-02486ab
Command: wp plugin (e.g. wp plugin list)
PHP 7.4.7

The wp plugin command does not find any plugins if we set WP_PLUGIN_DIR using `define( 'WP_PLUGIN_DIR', __DIR__ . '/world/' );` in my wp-config.
in 2.4.0 I get:
`/var/www/vhosts/hello/world/`

in 2.5.0 I get:
`phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/world/`

which is why suddenly the "plugin" command is broken in 2.5.0 (since my plugins are obviously not located in the phar directory)
So this definitely is a major bug, as wp cli completely changes the working directory and is therefore not running WP in the given path

**Comment by janw-me** [comment] 2020-10-01 11:36
![image](https://user-images.githubusercontent.com/1026882/94804354-f99d5380-03ea-11eb-82cb-fd8c01748baf.png)
I can confirm this for both `theme list` and `plugin list`

**Comment by schlessera** [comment] 2020-10-01 12:07
This will require fixing before v2.5.0 release.

**Comment by schlessera** [comment] 2020-10-02 07:28
I thought this test would replicate the above behavior, but it doesn't:
```gherkin
  # Regression test for https://github.com/wp-cli/extension-command/issues/247
  Scenario: __FILE__ and __DIR__ in wp-config.php don't point into the PHAR filesystem
    Given a WP installation
    And a new Phar with the same version
    And a wp-config.php file:
      """
      <?php
      define( 'DB_NAME', 'wp_cli_test' );
      define( 'DB_USER', '{DB_USER}' );
      define( 'DB_PASSWORD', '{DB_PASSWORD}' );
      define( 'DB_HOST', '{DB_HOST}' );
      define( 'DB_CHARSET', 'utf8' );
      define( 'DB_COLLATE', '' );
      $table_prefix = 'wp_';

      // Provide defines that make use of __FILE__ and __DIR__.
      define( 'WP_CONTENT_DIR', __FILE__ . '/my-plugins/' );
      define( 'WP_PLUGIN_DIR', __DIR__ . '/my-plugins/' );

      if ( ! defined( 'ABSPATH' ) )
        define( 'ABSPATH', dirname( __FILE__ ) . '/' );
      require_once( ABSPATH . 'wp-settings.php' );
      """

    When I run `{PHAR_PATH} eval "echo 'WP_CONTENT_DIR => ' . WP_CONTENT_DIR;"`
    Then STDOUT should not contain:
      """
      WP_CONTENT_DIR => phar://
      """

    When I run `{PHAR_PATH} eval "echo 'WP_PLUGIN_DIR => ' . WP_PLUGIN_DIR;"`
    Then STDOUT should not contain:
      """
      WP_PLUGIN_DIR => phar://
      """
```

Back to the drawing board...

**Comment by schlessera** [comment] 2020-10-02 07:44
Even when doing this manually, I cannot replicate the issue.

@janw-me In your case above, did you try `wp eval 'echo WP_PLUGIN_DIR;'` to see what it is set to?

**Comment by kkmuffme** [comment] 2020-10-02 07:55
Just checked again: as of (maybe prior) `WP-CLI 2.5.0-alpha-75cb7e3` the issue seems to be fixed and it works again as expected.

**Comment by janw-me** [comment] 2020-10-02 08:42
I still have the issue.
![image](https://user-images.githubusercontent.com/1026882/94904126-1db86d80-049b-11eb-9f66-d6a5b88dc2d5.png)

@schlessera 
I have set some specific constants, but not the one you asked for.

It occurs when I set `define( 'WP_CONTENT_DIR', dirname( __FILE__ ) . '/wp-content' );`
When I toggle that one off it works again.

**Comment by janw-me** [comment] 2020-10-07 18:52
After some digging I found the problem in the function `replace_path_consts` which was altered with [this commit](https://github.com/wp-cli/wp-cli/commit/896d7d7365679c1d772ed8c9eb775ba70ecc7097).

Which is meant to replace constants in a virtual `wp-config.php`

The difference:
![image](https://user-images.githubusercontent.com/1026882/95374641-e0ab0b80-08de-11eb-86e3-e2ad21b2a86a.png)

I hope to have another look next Wednesday, maybe sooner..

**Comment by schlessera** [comment] 2020-10-29 11:22
I still fail to replicate this. @janw-me I'm not sure I correctly understand your screenshot. What am I looking at? The diff looks like a manual change from you, not something that would have been replaced by WP-CLI...

**Comment by janw-me** [comment] 2020-11-04 14:53
This should be fixed with [PR5465](https://github.com/wp-cli/wp-cli/pull/5465).
I also tried to create a feature test, but so far unsuccessful.

**Closed** 2020-11-05 07:08 UTC
Labels: bug, command:plugin-list, command:theme-list
