### ISSUE TITLE
bug with update

### ISSUE THREAD

**Issue by RoundAboutWEB** [wp-cli/extension-command#193] opened 2019-08-17 14:59 UTC
![grafik](https://user-images.githubusercontent.com/26809494/63213737-32f40080-c110-11e9-8e64-eaf2631f35dc.png)

Is there a bug with "wp plugin update"?
For some plugin the command will show available updates, but there are no updates available.

**Comment by schlessera** [comment] 2019-08-25 07:12
Yes, indeed, it looks like there was a regression here. Latest version shows invalid updates where older versions didn't.

**Comment by ernilambar** [comment] 2024-04-16 05:41
With WP 6.5 and WP CLI 2.10, I could not reproduce this issue issue. Is this still valid?

**Comment by ernilambar** [comment] 2024-04-16 05:46
Closing this for now. We can reopen if issue arise again and we could find steps to reproduce this issue in new settings.

**Closed by ernilambar** 2024-04-16 05:46 UTC
Labels: bug
